service: saas-starter-auth-api

custom:
   projectName: saas-starter
   defaultRegion: us-east-1
   region: ${opt:region, self:custom.defaultRegion}
   stage: ${opt:stage, env:USER}
   writeEnvVars:
      SERVERLESS_STAGE: ${self:custom.stage}
      SERVERLESS_PROJECT: ${self:custom.projectName}
      SERVERLESS_SERVICE_NAME: ${self:service}

plugins:
   - serverless-plugin-write-env-vars

package:
   exclude:
      - 'node_modules/serverless-plugin-write-env-vars/**/*'
      - 'tests/**/*'

provider:
   name: aws
   runtime: nodejs4.3
   region: ${self:custom.region}
   stage: ${self:custom.stage}
   iamRoleStatements:
      - Effect: Allow
        Action:
           - 'logs:CreateLogGroup'
           - 'logs:CreateLogStream'
           - 'logs:PutLogEvents'
        Resource: 'arn:aws:logs:${self:custom.region}:*:*'

functions:
   ping:
      name: ${self:service}-${self:provider.stage}-ping
      handler: src/ping/Ping.handler
      memorySize: 128
      timeout: 2
      events:
         - http:
            method: GET
            path: ping
