service: saas-starter-auth-api

custom:
   projectName: saas-starter
   defaultRegion: us-east-1
   region: ${opt:region, self:custom.defaultRegion}
   stage: ${opt:stage, env:USER}

package:
   exclude:
      - 'node_modules/serverless-plugin-write-env-vars/**/*'
      - 'tests/**/*'

provider:
   name: aws
   runtime: nodejs4.3
   region: ${self:custom.region}
   stage: ${self:custom.stage}
   environment:
      SERVERLESS_STAGE: ${self:custom.stage}
      SERVERLESS_PROJECT: ${self:custom.projectName}
      SERVERLESS_SERVICE_NAME: ${self:service}
   iamRoleStatements:
      - Effect: Allow
        Action:
           - 'logs:CreateLogGroup'
           - 'logs:CreateLogStream'
           - 'logs:PutLogEvents'
        Resource: 'arn:aws:logs:${self:custom.region}:*:*'
      - Effect: Allow
        Action:
           - 'dynamodb:GetItem'
           - 'dynamodb:PutItem'
           - 'dynamodb:BatchGetItem'
           - 'dynamodb:Query'
        Resource: 'arn:aws:dynamodb:${self:custom.region}:*:table/${self:service}-${self:custom.stage}-*'
      - Effect: Allow
        Action:
           - 'dynamodb:GetItem'
           - 'dynamodb:BatchGetItem'
           - 'dynamodb:Query'
        Resource: 'arn:aws:dynamodb:${self:custom.region}:*:table/${self:service}-${self:custom.stage}-*/index/*'

functions:
   ping:
      name: ${self:service}-${self:provider.stage}-ping
      handler: src/ping/Ping.handler
      memorySize: 128
      timeout: 2
      events:
         - http:
            method: GET
            path: ping
   socialAuth:
      name: ${self:service}-${self:provider.stage}-socialAuth
      handler: src/social-auth/SocialAuthentication.handler
      memorySize: 512
      timeout: 4
      events:
         - http:
            method: POST
            path: social-auth

resources:
   Resources:
      UsersTable:
         Type: AWS::DynamoDB::Table
         Properties:
            TableName: ${self:service}-${self:custom.stage}-Users
            AttributeDefinitions:
               -
                  AttributeName: id
                  AttributeType: S
               -
                  AttributeName: emailAddress
                  AttributeType: S
            KeySchema:
               -
                  AttributeName: id
                  KeyType: HASH
            GlobalSecondaryIndexes:
               -
                  IndexName: emailAddress
                  Projection:
                     ProjectionType: KEYS_ONLY
                  KeySchema:
                     -
                        AttributeName: emailAddress
                        KeyType: HASH
                  ProvisionedThroughput:
                     ReadCapacityUnits: 1
                     WriteCapacityUnits: 1
            ProvisionedThroughput:
               ReadCapacityUnits: 1
               WriteCapacityUnits: 1
      LoginsTable:
         Type: AWS::DynamoDB::Table
         Properties:
            TableName: ${self:service}-${self:custom.stage}-Logins
            AttributeDefinitions:
               -
                  AttributeName: key
                  AttributeType: S
               -
                  AttributeName: userID
                  AttributeType: S
            KeySchema:
               -
                  AttributeName: key
                  KeyType: HASH
            GlobalSecondaryIndexes:
               -
                  IndexName: userID
                  Projection:
                     ProjectionType: KEYS_ONLY
                  KeySchema:
                     -
                        AttributeName: userID
                        KeyType: HASH
                  ProvisionedThroughput:
                     ReadCapacityUnits: 1
                     WriteCapacityUnits: 1
            ProvisionedThroughput:
               ReadCapacityUnits: 1
               WriteCapacityUnits: 1
      AccountsTable:
         Type: AWS::DynamoDB::Table
         Properties:
            TableName: ${self:service}-${self:custom.stage}-Accounts
            AttributeDefinitions:
               -
                  AttributeName: id
                  AttributeType: S
            KeySchema:
               -
                  AttributeName: id
                  KeyType: HASH
            ProvisionedThroughput:
               ReadCapacityUnits: 1
               WriteCapacityUnits: 1
